apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
    stage: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
      stage: prod
  template:
    metadata:
      labels:
        service: payment
        stage: prod
    spec:
      serviceAccountName: robot-shop
      containers:
      - name: payment
        image: robotshop/rs-payment:latest
        imagePullPolicy: IfNotPresent
        # agent networking access
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: PAYMENT_GATEWAY
            value: null
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
  labels:
    service: payment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: payment